import { Strings } from '.';

const english: Strings = {
	LOGIN: 'Login',
	USERNAME: 'Username',
	PASSWORD: 'Password',
	ENTER_USERNAME: 'Enter your username',
	ENTER_PASSWORD: 'Enter your password',
	OK: 'Okay',
	YES: 'Yes',
	CANCEL: 'Cancel',
	HIDE: 'Hide',
	SHOW: 'Show',
	USERNAME_OR_PASSWORD_NOT_ENTERED: 'Oops, you forget to enter your username/password',
	LOGIN_FAILED: 'Username or password is invalid',
	HELLO: 'Hello,',
	PROFILE: 'Profile',
	ABOUT_US: 'About',
	LOGOUT: 'Logout',
	LOGOUT_WAITING: 'Logout, please be patient',
	MY_COURSES: 'My Courses',
	USERS: 'Users',
	COURSES: 'Courses',
	DEPARTMENTS: 'Departments',
	ENROLL_TO_COURSE: 'Assign to course',
	LOGOUT_U_SURE: 'Are you sure that you want to logout?',
	SEARCH_DEPARTMENT: 'Search department by',
	CODE: 'Code',
	ENTER_CODE_TO_SEARCH: 'Enter code here',
	NAME: 'Name',
	FULL_NAME: 'Full name',
	ENTER_NAME_TO_SEARCH: 'Enter name here',
	SETTINGS: 'Settings',
	ADD_NEW_DEPARTMENT: 'Add new department',
	ADD_NEW_ROW: 'Add new row',
	DELETE_ALL_DEPARTMENT: 'Delete all departments',
	ARE_YOU_SURE: 'Do you sure?',
	SEARCH: 'Search',
	CLEAR: 'Clear',
	NO_RESULT_FOUND: 'No result found',
	RESULT: 'Result',
	OPTIONS: 'Options',
	NEXT: 'Next',
	PREV: 'Prev',
	DELETE: 'DELETE',
	EDIT: 'Edit',
	ACTIONS: 'Actions',
	EDIT_DEPARTMENT: 'Edit Department',
	CLOSE: 'Close',
	SAVE: 'Save',
	ADD_DEPARTMENT: 'Add new departments',
	SORT_ASC: 'Sort Asc',
	SORT_DESC: 'Sort Desc',
	IMPORT_FILE: 'Import by file',
	ENTER_ONE_ROW: 'Please enter at least one row',
	CHECK_YOUR_INFO: 'There is problem with your info please check it and try again',
	CREATED: 'Created!',
	DELETE_ALL_COURSE: 'Delete all courses',
	ADD_NEW_COURSE: 'Add new course',
	SEARCH_COURSE: 'Search course',
	ADD_COURSE: 'Add course',
	EDIT_COURSE: 'Edit course',
	ASSIGN_LECTURER: 'Assign lecturer',
	ADD_LECTURER_BY_ID: 'Add lecturer by id',
	LECTURER_ID: 'Lecturer id',
	ADD: 'Add',
	ADDED: 'Added',
	ID: 'ID',
	EDIT_USER: 'Edit user',
	ENTER_NAME: 'Enter name',
	ENTER_ID: 'Enter id',
	ADD_USER: 'Add user',
	SEARCH_USER: 'Search user',
	ENTER_ID_TO_SEARCH: 'Enter id to search',
	ADD_NEW_USERS: 'Add new users',
	DELETE_ALL_USERS: 'Delete all users',
	FIRST_NAME: 'First',
	LAST_NAME: 'Last',
	EMAIL: 'Email',
	ENTER_FIRST_NAME: 'Enter first name',
	ENTER_LAST_NAME: 'Enter last name',
	ENTER_EMAIL: 'Enter email',
	ROLE: 'Role',
	NO_SELECTION: 'No selection',
	PLEASE_ENTER_ROLE: 'Please enter role',
	NO_COURSE_FOUND: 'No course found',
	ADD_OR_REMOVE_SOFTWARE: 'Add/Remove software',
	SOFTWARE: 'Software',
	ADD_NEW_SOFTWARE: 'Add new software',
	VERSION: 'Version',
	SELECT: 'Select',
	SELECT_SOFTWARE_FIRST: 'Please select software first',
	REMOVED: 'Removed',
	SHOW_ALL_SELECTED_COURSES: 'Show all selected',
	ENROLL_TO_SELECTED_COURSES: 'Enroll to selected',
	INSTALL_OR_UPDATE_SOFTWARE: 'Install or update software',
	SOFTWARE_NEED_TO_INSTALL: 'Software to install',
	SOFTWARE_NEED_TO_REMOVE: 'Software to remove',
	NOTHING_TO_INSTALL_OR_REMOVE: 'Nothing to install or remove',
	REMOVE: 'Remove',
	MY_PROFILE: 'My Profile',
	EDIT_PROFILE: 'Edit Profile',
	CHANGE_PASSWORD: 'Change password',
	CURRENT_PASSWORD: 'Current password',
	SET_NEW_PASSWORD: 'New password',
	CONFIRM_PASSWORD: 'Confirm password',
	PROJECT_STORY: 'Project story',
	PASSWORD_CHANGED: 'Your password has been changed',
	PASSWORD_NOT_MATCHED: 'Your new password does not matched',
	FILL_ALL_FIELDS: 'Please fill all fields',
	WRONG_CURRENT_PASSWORD: 'Wrong current password',
	PASSWORD_TOO_SHORT: 'New password too short',
	FIRST_NAME_PROFILE: 'First Name',
	LAST_NAME_PROFILE: 'Last Name',
	PASSWORD_LENGTH: 'Password must contain 5-15 characters',
};

export default english;
