import { Strings } from '.';

const english: Strings = {
	LOGIN: 'Login',
	USERNAME: 'Username',
	PASSWORD: 'Password',
	ENTER_USERNAME: 'Enter your username',
	ENTER_PASSWORD: 'Enter your password',
	OK: 'Okay',
	YES: 'Yes',
	CANCEL: 'Cancel',
	HIDE: 'Hide',
	SHOW: 'Show',
	USERNAME_OR_PASSWORD_NOT_ENTERED: 'Oops, you forget to enter your username/password',
	LOGIN_FAILED: 'Username or password is invalid',
	HELLO: 'Hello,',
	PROFILE: 'Profile',
	ABOUT_US: 'About Us',
	LOGOUT: 'Logout',
	LOGOUT_WAITING: 'Logout, please be patient',
	MY_COURSES: 'My Courses',
	USERS: 'Users',
	COURSES: 'Courses',
	DEPARTMENTS: 'Departments',
	ENROLL_TO_COURSE: 'Assign to course',
	LOGOUT_U_SURE: 'Are you sure that you want to logout?',
	SEARCH_DEPARTMENT: 'Search department by',
	CODE: 'Code',
	ENTER_CODE_TO_SEARCH: 'Enter code here',
	NAME: 'Name',
	FULL_NAME: 'Full name',
	ENTER_NAME_TO_SEARCH: 'Enter name here',
	SETTINGS: 'Settings',
	ADD_NEW_DEPARTMENT: 'Add new department',
	ADD_NEW_ROW: 'Add new row',
	DELETE_ALL_DEPARTMENT: 'Delete all departments',
	ARE_YOU_SURE: 'Do you sure?',
	SEARCH: 'Search',
	CLEAR: 'Clear',
	NO_RESULT_FOUND: 'No result found',
	RESULT: 'Result',
	OPTIONS: 'Options',
	NEXT: 'Next',
	PREV: 'Prev',
	DELETE: 'DELETE',
	EDIT: 'Edit',
	ACTIONS: 'Actions',
	EDIT_DEPARTMENT: 'Edit Department',
	CLOSE: 'Close',
	SAVE: 'Save',
	ADD_DEPARTMENT: 'Add new departments',
	SORT_ASC: 'Sort Asc',
	SORT_DESC: 'Sort Desc',
	IMPORT_FILE: 'Import by file',
	ENTER_ONE_ROW: 'Please enter at least one row',
	CHECK_YOUR_INFO: 'There is problem with your info please check it and try again',
	CREATED: 'Created!',
	DELETE_ALL_COURSE: 'Delete all courses',
	ADD_NEW_COURSE: 'Add new course',
	SEARCH_COURSE: 'Search course',
	ADD_COURSE: 'Add course',
	EDIT_COURSE: 'Edit course',
};

export default english;
