import { Strings } from '.';

const english: Strings = {
	LOGIN: 'Login',
	USERNAME: 'Username',
	PASSWORD: 'Password',
	ENTER_USERNAME: 'Enter your username',
	ENTER_PASSWORD: 'Enter your password',
	OK: 'Okay',
	CANCEL: 'Cancel',
	HIDE: 'Hide',
	SHOW: 'Show',
	USERNAME_OR_PASSWORD_NOT_ENTERED: 'Oops, you forget to enter your username/password',
	LOGIN_FAILED: 'Username or password is invalid',
	HELLO: 'Hello,',
	PROFILE: 'Profile',
	ABOUT_US: 'About Us',
	LOGOUT: 'Logout',
	LOGOUT_WAITING: 'Logout, please be patient',
	MY_COURSES: 'My Courses',
	USERS: 'Users',
	COURSES: 'Courses',
	DEPARTMENTS: 'Departments',
	ENROLL_TO_COURSE: 'Assign to course',
	LOGOUT_U_SURE: 'Are you sure that you want to logout?',
	SEARCH_DEPARTMENT: 'Search department by',
	CODE: 'Code:',
	ENTER_CODE_TO_SEARCH: 'Enter name here',
	NAME: 'Name:',
	ENTER_NAME_TO_SEARCH: 'Enter name code',
	SETTINGS: 'Settings',
	ADD_NEW_DEPARTMENT: 'Add new department',
	DELETE_ALL_DEPARTMENT: 'Delete all departments',
	SEARCH: 'Search',
	CLEAR: 'Clear',
};

export default english;
